import "./globals.css";
import { Inter } from "next/font/google";
import { PlayerCLient, SessionProviderTag } from "@/components/client";
import SlideBar from "@/components/SlideBar";
import Player from "@/components/Player/Player";
import React from "react";
import Head from "next/head";
import Script from "next/script";
// import { useRecoilValue } from "recoil";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // <Head>
  <Script src="https://sdk.scdn.co/spotify-player.js"></Script>;
  {
    /* </Head>; */
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProviderTag>
          <React.StrictMode>
            <div className="bg-black ">
              <div className="flex overflow-hidden ">
                <SlideBar />
                {children}
              </div>
              <PlayerCLient></PlayerCLient>
            </div>
          </React.StrictMode>
        </SessionProviderTag>
      </body>
    </html>
  );
}
